"use client";
import { FormEvent, useState } from "react";
import type { Plan, Validation } from "@/lib/schemas";

type Result = { status: string; source: string; attempts: { revision: number; plan: Plan; validation: Validation }[]; publishedPlan: Plan; adaptedPlan: Plan };
const initial = { goal: "Kas kazanmak", level: "Başlangıç", weeklyDays: 3, duration: 45, equipment: "Dumbbell ve vücut ağırlığı", limitations: "Diz hassasiyeti" };

function PlanView({ plan, adapted = false }: { plan: Plan; adapted?: boolean }) {
  return <section className={`plan ${adapted ? "adapted" : ""}`}><div className="planHead"><div><span className="eyebrow">{adapted ? "ADAPTED PLAN" : "PUBLISHED PLAN"}</span><h2>{plan.title}</h2><p>{plan.summary}</p></div><span className="approved">✓ Onaylandı</span></div><div className="calendar">{plan.days.map((day, i) => <article className="day" key={day.day}><div className="dayTop"><span>0{i + 1}</span><div><h3>{day.day}</h3><small>{day.focus}</small></div><b>{day.estimatedDuration} dk</b></div>{day.exercises.map(e => <div className="exercise" key={e.name}><strong>{e.name}</strong><span>{e.sets} set × {e.reps}</span><small>{e.restSeconds} sn dinlenme · ~{e.estimatedMinutes} dk</small></div>)}</article>)}</div></section>;
}

export default function Home() {
  const [profile, setProfile] = useState(initial); const [completion, setCompletion] = useState(100); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function run(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); setResult(null); try { const res = await fetch("/api/plan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profile, completion }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Plan doğrulanamadı"); setResult(data); } catch (err) { setError(err instanceof Error ? err.message : "Hata oluştu"); } finally { setLoading(false); } }
  async function readapt(value: number) { setCompletion(value); if (!result) return; const res = await fetch("/api/plan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profile, completion: value }) }); setResult(await res.json()); }
  const stages = ["Generating", "Validating", ...(result?.attempts.some(a => a.revision > 0) ? ["Revising"] : []), "Published", "Adapted"];
  return <main><header><a className="brand"><span>F</span> FORM<span>FLOW</span></a><div className="status"><i /> MULTI-AGENT SYSTEM · ONLINE</div></header><div className="hero"><div><span className="eyebrow">AI TRAINING ARCHITECT</span><h1>Planla. Doğrula.<br/><em>İlerle.</em></h1><p>Hedeflerine özel üretilen, güvenlik kontrollerinden geçen ve performansına göre adapte olan akıllı antrenman planı.</p></div><div className="metric"><strong>3</strong><span>BAĞIMSIZ<br/>AGENT</span></div></div>
  <div className="grid"><aside><form onSubmit={run}><div className="sectionTitle"><span>01</span><div><h2>Profilini oluştur</h2><p>Agent&apos;ların seni tanımasını sağla.</p></div></div><label>HEDEF<input value={profile.goal} onChange={e => setProfile({...profile, goal:e.target.value})}/></label><div className="row"><label>SEVİYE<select value={profile.level} onChange={e => setProfile({...profile, level:e.target.value})}><option>Başlangıç</option><option>Orta</option><option>İleri</option></select></label><label>HAFTALIK GÜN<input type="number" min="1" max="7" value={profile.weeklyDays} onChange={e => setProfile({...profile, weeklyDays:+e.target.value})}/></label></div><label>SEANS SÜRESİ <b>{profile.duration} DK</b><input type="range" min="15" max="90" step="5" value={profile.duration} onChange={e => setProfile({...profile, duration:+e.target.value})}/></label><label>EKİPMAN<input value={profile.equipment} onChange={e => setProfile({...profile, equipment:e.target.value})}/></label><label>FİZİKSEL KISITLAMA<textarea value={profile.limitations} onChange={e => setProfile({...profile, limitations:e.target.value})}/></label><button disabled={loading}>{loading ? "AGENT'LAR ÇALIŞIYOR..." : "PLANIMI OLUŞTUR →"}</button></form><div className="privacy">◆ Verilerin yalnızca plan üretimi için kullanılır.</div></aside>
  <div className="content"><div className="pipeline"><div className="sectionTitle"><span>02</span><div><h2>Agent Pipeline</h2><p>Her adım bağımsız çalışır ve doğrulanır.</p></div></div><div className="steps">{["Generating","Validating","Revising","Published","Adapted"].map((s,i) => <div className={(loading && i < 2) || result && stages.includes(s) ? "active" : ""} key={s}><i>{result && stages.includes(s) ? "✓" : i+1}</i><span>{s}<small>{["Plan Generator Agent","Plan Validator Agent","Gerekirse · maks. 2","Yalnızca approved","Performansa göre"][i]}</small></span></div>)}</div>{result && <div className="audit"><strong>Validator geri bildirimi</strong>{result.attempts.map((a,i) => <p key={i}><span className={a.validation.approved ? "ok":"bad"}>{a.validation.approved ? "APPROVED":"REJECTED"}</span> Deneme {i+1}: {a.validation.feedback.join(" · ") || "Tüm süre, ekipman, kısıtlama, alan ve gün sayısı kontrolleri geçti."}</p>)}<small>Kaynak: {result.source === "demo" ? "Deterministik demo fallback" : "OpenAI modeli"}</small></div>}</div>{error && <div className="error">{error}</div>}{result?.publishedPlan && <PlanView plan={result.publishedPlan}/>} {result?.adaptedPlan && <><div className="completion"><div><span className="eyebrow">HAFTALIK CHECK-IN</span><h2>Bu haftayı ne kadar tamamladın?</h2></div><div>{[100,70,40].map(n=><button className={completion===n?"selected":""} onClick={()=>readapt(n)} key={n}>%{n}</button>)}</div></div><PlanView plan={result.adaptedPlan} adapted/></>}</div></div></main>;
}
